#!/bin/bash

# for d in $@; do
#   cp t $d/schema.ex
#   up="$(tr '[:lower:]' '[:upper:]' <<< ${d:0:1})${d:1}"
#   sed -i '' -e s/XXX/$up/ $d/schema.ex
# done
prefix=1
steps=100
app=auth

next=0
for d in $@; do
  name=$(basename $d)
  upname="$(tr '[:lower:]' '[:upper:]' <<< ${name:0:1})${name:1}"
  next=$(expr $next + $steps)
  file=$(printf "0001%010d_BASE_${app}_${name}.exs" $next)
  # ln -
  echo ln -s ../../../lib/$d/schema.ex $file
  ln -s ../../../lib/$d/schema.ex $file

done
